### ISSUE TITLE
Impossible to access an attribute ("name") on a NULL variable ("") in SonataPageBundle::base_layout.html.twig at line 80 

### ISSUE THREAD

**Issue by RomainTweaks** [sonata-project/sandbox#498] opened 2015-04-14 12:36 UTC
Hello,

I have juste install the sonata sandbox project. I executed all commands line : 
- For add my site (php app/console sonata:page:create-site) I'm in local on windows 8 with Xampp
- To generate the pages core route (php app/console sonata:page:update-core-routes --site=2)
- To generate snapshots (php app/console sonata:page:create-snapshots)

But when I'm trying to display a page I get the error : 
`Impossible to access an attribute ("name") on a NULL variable ("") in SonataPageBundle::base_layout.html.twig at line 80`

SonataPageBundle::base_layout.html.twig at line 80 corresponding to the following code : 

``` twig
{% if sites|length > 1 and site is defined %}
     <li class="dropdown">
           <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ site.name }} <span class="caret"></span></a>
           <ul class="dropdown-menu">
                {% for site in sites %}
                    <li><a href="{{ site.url }}">{{ site.name }}</a></li>
                {% endfor %}
           </ul>
    </li>
{% endif %}
```

I don't understand where the variable {{ site }} is set  and why is null because when I execute the command line `php app/console sonata:page:create-site` I have successfull created my site.

On the contrary I can access to the admin interface.

Anyone can help me?? :)

**Comment by nlzet** [comment] 2015-04-14 18:02
Not sure about the sites|length, but i guess that $site = null is still a defined variable with a value of null.

Are you sture line 80 of the base_layout template is the `<a href` lin ?

**Comment by rande** [comment] 2015-04-20 09:43
@nlzet the PageServiceManager provide the site variable. Can you review that the site is correctly set to the page and the PageServiceManager is called

**Comment by kachraf** [comment] 2016-04-20 15:55
Hello, I got same thing, I fixed it by not putting "http" in the host field

**Comment by jordisala1991** [comment] 2018-04-01 11:29
Closing because this issue is super old and not placed on the correct bundle. If you still having this error please report on PageBundle.

If you think this error is related to some code on the sandbox and it is reproducible on the 3.0 branch, please ping me to reopen.

**Closed by jordisala1991** 2018-04-01 11:29 UTC
