### ISSUE TITLE
Serialization of 'Closure' is not allowed

### ISSUE THREAD

**Issue by Vermond125** [sonata-project/sandbox#436] opened 2014-12-10 21:36 UTC
Hello! I have a broblem when i'm trying to create a new Product (using product bundle) and even new Post (using news bundle).

After going to create action i see "Serialization of 'Closure' is not allowed".
I'm using "sonata-project/sandbox": "dev-master".
![db9ae263d7c45bd0f15d6c24d3064a0a](https://cloud.githubusercontent.com/assets/8845418/5384804/a23b4d5a-80cd-11e4-9700-cc6519264217.png)
What can it be?

**Comment by rande** [comment] 2015-01-05 14:56
This issue was caused by SonataFormatterBundle. It is now fixed.

**Closed by rande** 2015-01-05 14:56 UTC
