### ISSUE TITLE
Login to backend

### ISSUE THREAD

**Issue by malutanpetronel** [sonata-project/sandbox#558] opened 2015-11-05 19:46 UTC
All tryings to login with admin / admin are redirecting to homepage...
Tried the 2.3, 2.4 new method for install mentioned in comments on sonata demo project getging started.

Any help for this ? Anyone else experience the same ?

**Comment by samvdb** [comment] 2015-11-20 11:55
I can confirm that you are not the only one. Which OS are you using?

**Comment by malutanpetronel** [comment] 2015-11-23 12:24
windows 8 with vagrant ubuntu machine

**Comment by OskarStark** [comment] 2015-11-24 21:42
@rande can you help`

**Comment by Jabbaa** [comment] 2016-02-28 17:14
I can confirm that, too. I did a clean install of the sandbox and every time I do a login on "/admin" with valid credentials, I'll be redirected to "/" and still be "anon".
This happens on 2.3. and 2.4. in all browsers.

Can somebody help, please?

**Comment by jjborie** [comment] 2016-02-28 17:31
I have being in the same kind of problem recently, the problem was related to configuration of session.
If it's the case, your cookie "phpsessid" is changed on every call of each page, can you confirm ?

Double check also that you are allowing cookies on your browser for the sandbox.
Can you share your php.ini? What php version are you using?
If you are using sessions stored on files, ensure you have right access for the folder.

**Comment by Jabbaa** [comment] 2016-02-28 17:45
@jjborie Many thanks for your quick reply. I was using php5.6.
Yes, it was permission stuff but it relies on the nfs-share. After changing the save_path to a non-shared folder on the VM the problem was solved.

**Comment by jordisala1991** [comment] 2018-04-01 10:16
Seems like a problem with configuration. If it is not, probably it is related to SonataUserBundle instead.

Closing for now, if you think this issue belongs here, please ping me to reopen

**Closed by jordisala1991** 2018-04-01 10:16 UTC
