### ISSUE TITLE
Paypal payment issue

### ISSUE THREAD

**Issue by danvbe** [sonata-project/sandbox#401] opened 2014-07-25 12:25 UTC
I tried to setup Paypal Payment method and I had some issues:
1. The documentation is not updated with current config. The [index file](http://sonata-project.org/bundles/ecommerce/develop/doc/reference/bundles/payment/index.html) seems to be fine, but the [Paypal specific file](http://sonata-project.org/bundles/ecommerce/develop/doc/reference/bundles/payment/paypal.html) is not updated (the default configuration). This is not so important, but I thought I should mention it.
2. The [Paypal class](https://github.com/sonata-project/ecommerce/blob/master/src/Component/Payment/Paypal.php) in the ecommerce bundle was not working well. In the `public function sendbank(OrderInterface $order)` function, where we are setting up the fields to be sent to paypal, we have:
   
   ```
   ... ...
   'amount'        => $order->getTotalInc(),
   'currency_code' => $order->getCurrency(),
   .... ....
   ```

The `$order->getTotalInc()` returned the value with 3 decimals (I assume it does this because we have `bcscale(3);` set in `AppKernel::init()`), but this is generating an error on Paypal (it expects 2 decimal values).
The `$order->getCurrency()` was returning a serialized object... this is from the output:

```
   [currency_code] => Sonata\Component\Currency\Currency Object
      (
          [label:protected] => EUR
      )
```

I have managed to fix this by creating in ApplicationPaymentBundle my custom Paypal class (extended from [Sonata\Component\Payment\Paypal](https://github.com/sonata-project/ecommerce/blob/master/src/Component/Payment/Paypal.php), overwriting the `sendBanck(...)` function by fixing `amount` and `currency_code` and changing the `sonata.payment.method.paypal.class` parameter to point to this new class.

As solution... I would suggest to implement these changes directly in the ecommerce bundle (in [Paypal class](https://github.com/sonata-project/ecommerce/blob/master/src/Component/Payment/Paypal.php)) as they are directly related and specific to Paypal (and do not really require to be done at Application level, via extending).

**Comment by jordisala1991** [comment] 2018-02-17 15:09
Since the issue is already on ecommerce, I am closing this one

**Closed by jordisala1991** 2018-02-17 15:09 UTC
Labels: bug
