### ISSUE TITLE
Problem when create new block.

### ISSUE THREAD

**Issue by tranthienbinh1989** [sonata-project/sandbox#489] opened 2015-04-02 09:12 UTC
Hello,
I got this error when I try to create a new block on CMS.

Method "blockMetadata" for object "Sonata\PageBundle\Block\ContainerBlockService" does not exist in SonataPageBundle:BlockAdmin:select_type.html.twig at line 30

More information:
vesion : 2.3.x-dev
Composer.json

"require": {
        "php": ">=5.3.3",
        "ext-bcmath" : "*",

```
    "twig/twig": "~1.12",
    "twig/extensions": "~1.0",

    "symfony/symfony": "~2.5",
    "symfony/assetic-bundle": "~2.3",
    "symfony/swiftmailer-bundle": "~2.3",
    "symfony/monolog-bundle": "~2.3",

    "sensio/distribution-bundle": "~2.3",
    "sensio/framework-extra-bundle": "~2.3",
    "sensio/generator-bundle": "~2.3",

    "jms/security-extra-bundle": "~1.5",
    "jms/di-extra-bundle": "~1.4",
    "jms/serializer-bundle": "~0.11",

    "doctrine/orm": "~2.4",
    "doctrine/doctrine-bundle": "~1.2",
    "doctrine/doctrine-migrations-bundle": "~2.0dev",
    "doctrine/migrations": "~1.0@dev",
    "doctrine/doctrine-fixtures-bundle": "~2.2",
    "doctrine/data-fixtures": "~1.0@dev",

    "symfony-cmf/routing-bundle": "~1.1",

    "knplabs/gaufrette": "0.1.4",
    "knplabs/knp-menu-bundle": "~2.0",

    "sonata-project/datagrid-bundle": "2.2.*@dev",
    "sonata-project/easy-extends-bundle": "~2.1",
    "sonata-project/seo-bundle": "~1",
    "sonata-project/doctrine-extensions": "~1",
    "sonata-project/intl-bundle": "~2.1",
    "sonata-project/admin-bundle": "~2.2",
    "sonata-project/doctrine-orm-admin-bundle": "~2.2",
    "sonata-project/notification-bundle": "~2.2",
    "sonata-project/block-bundle": "~2.2",
    "sonata-project/media-bundle": "~2.2",
    "sonata-project/user-bundle": "~2.2",
    "sonata-project/cache-bundle": "~2.1",
    "sonata-project/page-bundle": "~2.3",
    "sonata-project/formatter-bundle": "~2.3",
    "sonata-project/news-bundle": "~2.3",
    "sonata-project/exporter": "~1.3",
    "sonata-project/timeline-bundle": "~2.2,<2.3",
    "sonata-project/classification-bundle": "~2.2",
    "sonata-project/ecommerce": "dev-develop-deprecated",
    "sonata-project/comment-bundle": "~2.2@dev",

    "friendsofsymfony/comment-bundle": "~2.0@dev",

    "dflydev/markdown": "~1.0",
    "simplethings/entity-audit-bundle": "~0.5",
    "willdurand/faker-bundle": "~1.0",

    "mopa/bootstrap-bundle": "v3.0.0-beta3",
    "twbs/bootstrap": "v3.0.0",

    "stof/doctrine-extensions-bundle": "~1.1",
    "stephpy/TimelineBundle": "~2.0@dev",
    "stephpy/timeline": "~1.0@dev",

    "incenteev/composer-parameter-handler": "~2.0"
},
```

**Comment by informatico-madrid** [comment] 2015-04-11 15:22
I have the crear un block service estendiendo la clase ShareBlocSservice

**Comment by hvanoch** [comment] 2015-05-09 20:55
Have you found any solution for this?

**Comment by tranthienbinh1989** [comment] 2015-05-11 10:30
I think the problem is the sandbox is not up to date with some sonata bundle.

**Comment by davideugenepeterson** [comment] 2015-05-13 13:54
Does anyone have a fix for this, i'm having the same problem.

**Comment by hvanoch** [comment] 2015-05-13 14:15
Yes. Problem is indeed that some repositories are not in sync.
Problem is caused by https://github.com/sonata-project/SonataPageBundle/commit/0b577fd4e7c7810586eb6879300507e85c5c269b

I fixed it by using the old template.

create a custom template in app/Resources/SonataPageBundle/views/BlockAdmin/select_type.html.twig

copy the old version of the commit.

That should work :-)

**Comment by jordisala1991** [comment] 2018-04-01 10:29
Please use 3.0 of sandbox. This issue is related to old Sonata versions

**Closed by jordisala1991** 2018-04-01 10:29 UTC
